# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{right_git}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tony Spataro", "Scott Messier"]
  s.date = %q{2013-08-30}
  s.description = %q{An assortment of git-related classes created by RightScale.}
  s.email = %q{support@rightscale.com}
  s.extra_rdoc_files = [
    "CHANGELOG.rdoc",
    "LICENSE",
    "README.rdoc"
  ]
  s.homepage = %q{https://github.com/rightscale/right_git}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Reusable Git repository management code.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0.8.7", "< 0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<nokogiri>, ["= 1.5.6"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.7", "< 0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<nokogiri>, ["= 1.5.6"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.7", "< 0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<nokogiri>, ["= 1.5.6"])
  end
end

